# serverless.yml

service: apollo-lambda
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  memorySize: 512

plugins:
  - serverless-offline
  # - serverless-plugin-typescript

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    layers:
      - {Ref: ApolloLibLambdaLayer}
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

layers: 
  apolloLib: 
    path: layer
    compatibleRuntimes: 
      - nodejs12.x
